version: '3.8'

services:
  app:
    image: rosaapi
    build: .
    container_name: api_backend_rosa
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://db:3306/rosa_api?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=lucas2010
      - IP_STATIC1=http://localhost:8080
      - IP_STATIC2=http://192.168.1.34:8080
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=65464534
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: db_backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: lucas2010
      MYSQL_DATABASE: rosa_api
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
